package org.example.rediscartservice.domain.model.product;

import jakarta.validation.constraints.*;
import lombok.*;

import java.math.BigDecimal;

/**
 * Aggregate root for products (pure domain + Bean Validation).
 */
@Getter
@EqualsAndHashCode(of = "id")     // identity by id
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class Product {

    @NotBlank
    private String id;              // UUID string (generated by service/factory)

    @NotBlank
    private String sku;             // business key

    @NotBlank
    private String name;

    @Size(max = 10_000)
    private String description;

    @NotNull
    @DecimalMin(value = "0.00")
    @Digits(integer = 12, fraction = 2)
    private BigDecimal price;
}
